[mypy]
python_version = 3.11
strict = True
ignore_missing_imports = True
plugins = pydantic.mypy
mypy_path = layers/fishing_common

[mypy-lambdas.*]
ignore_missing_imports = True

[mypy-moto.*]
ignore_errors = True

[mypy-botocore.*]
ignore_missing_imports = True
